### PR TITLE
Delete unused apache config

### PR DESCRIPTION
**Pull request by jdreesen**
This skeleton uses nginx as its webserver and Pimcore's docker images don't support Apache anymore, so I think this file could be deleted.

### CODE REVIEW

**Comment by fashxp** [comment]
it should also be possible to use that skeleton with apache, right?

**Comment by jdreesen** [comment]
That's the question. Which config do you want to deliver out of the box? Should Apache be supported, even if the Pimcore docker container don't support it anymore? Which other webservers should be supported then? Maybe it's enough if config for other webservers can be copied from the docs?

**Comment by brusch** [comment]
I'd see this independent from Docker and just ship it for those who prefer Apache. 
An alternative would be to add this config somewhere to the docs ...

**Comment by jdreesen** [comment]
These docs should probably be updated anyways: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration.html

**Comment by dvesh3** [comment]
@jdreesen thanks!

**Pull request merged**
