### PR TITLE
Improve php-cs-fixer setup

### PR DESCRIPTION
**Pull request by yariksheptykin**
This PR:
- adds cs-fixer as a dev dependency
- registers add tests directory with the cs-fixer
- executed cs-fixer within github actions

### CODE REVIEW

**Comment by mattamon** [comment]
Hey @yariksheptykin thank you for your contribution.

Unfortunately we cannot accept it. The CS-Fixer rules are a company managed topic. Changing those rules needs to be considered for every bundle.

In such cases it is always better to open up a issue/discussion first, so we can evaluate the situation and give you feedback beforehand.

**Comment by yariksheptykin** [comment]
Hey @mattamon ! I don't understand what you mean. Do you mean that you at pimcore want to have a uniform cs-fixer ruleset that applies to all bundles and the skeleton? And you suggest to open issue first to duscuss which rules should go into the ruleset?

To clarify: my vision for this PR was to make use of the file that is already being shipped with the skeleton. I wanted to make sure that this file stays up to date, therefore I added cs-lint to CI. I also wanted to fix cs for the sources we ship with the skeleton. Whoever creates a new pimcore project from the skeleton should be able to quickly set up cs fixer, and the first commit should not be: "fixing cs in skeleton sources".

**Comment by yariksheptykin** [comment]
@mattamon your PR https://github.com/pimcore/skeleton/pull/188 is a better option. Feel free to close this one. We can start an issue to collect reasonable CS rules, which we can share pimcore-wide if you think it makes sense.

**Comment by mattamon** [comment]
@yariksheptykin Okay thank you! I will close your PR and merge mine. 

It would be awesome if you could open up a discussion! https://github.com/orgs/pimcore/discussions

**Pull request closed without merging**
