### PR TITLE
Kick duplicate nginx image/avif config

### LINKED ISSUE #161: [Bug]: Duplicate extension "avif", content type
### Expected behavior

No errors or warnings from Nginx when starting up. Can you reproduce this issue?

### Actual behavior

With Nginx 1.24 we get the following warning on starting the container:

```log
2023-07-25 10:38:43 nginx: [warn] duplicate extension "avif", content type: "image/avif", previous content type: "image/avif" in /etc/nginx/conf.d/default.conf:5
2023-07-25 10:38:43 nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2023-07-25 10:38:43 nginx: configuration file /etc/nginx/nginx.conf test is successful
```

The content type appears to already be defined in newer versions on Nginx, see:
Screenshot 2023-07-25 at 10 53 55

### Steps to reproduce

These lines may not be required.

https://github.com/pimcore/skeleton/blob/31a0daef0c3d996b677d8bd51f77fe3ef5030f2d/.docker/nginx.conf#L2-L6

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #161

### Additional Info
The config was added temporarily to fix the avif formats and now available in the stable image. please see https://github.com/pimcore/skeleton/pull/95#discussion_r869242356

### CODE REVIEW

**Comment by dvesh3** [comment]
Fixed by #530

**Comment by jdreesen** [comment]
What's #530? You mean in the demo? How should that fix it here?

**Comment by dvesh3** [comment]
Oh, sorry, I wanted to close the issue #161 😄

**Comment by jdreesen** [comment]
So this still needs to be merged, right?

**Comment by dvesh3** [comment]
yes, right. but can't since the branch is deleted so i'll push it directly. thanks for bringing this up :)

**Comment by dvesh3** [comment]
done 5377528a16bc3050a98f7d607b28a3dd2324fcb4

**Pull request closed without merging**
