### PR TITLE
Env var fix dcp

### PR DESCRIPTION
**Pull request by HaaseIT**
PHP environment variables did not work (linux at least), breaking xDebug.

### CODE REVIEW

**Comment by brusch** [comment]
Interesting ... this is how it's documented, and works for me ... see: 
https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

**Comment by HaaseIT** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
https://docs.docker.com/compose/compose-file/compose-file-v2/#environment

Both variants are allowed there, but only the variant with the colon work for me, on debian bullseye.

Docker version 20.10.5+dfsg1, build 55c4c88
docker-compose version 1.25.0

**Comment by brusch** [comment]
Hmm, interesting,  I'm also on bullseye 🤔 but yes, if both work,  I'm fine as well 😉

**Comment by brusch** [comment]
Fixed here as well: pimcore/demo#261

**Pull request merged**
