### PR TITLE
Support static pages in nginx

### PR DESCRIPTION
**Pull request by jdreesen**
Currently, static pages are only supported in the (unused) `.htaccess` config (since #58).

This PR adds support for static pages in nginx.

### CODE REVIEW

**Comment by jdreesen** [comment]
If you like this approach using a `map`, I'd update the Pimcore docs and the demo, too.

**Comment by fashxp** [comment]
related to https://github.com/pimcore/demo/pull/283

**Comment by jdreesen** [comment]
Should I update the docs and demo to use this approach, too?

**Comment by dvesh3** [comment]
> Should I update the docs and demo to use this approach, too?

@jdreesen yes, please. thanks!

**Pull request merged**
