### PR TITLE
Import docker-compose project by dpfaffenbauer

### PR DESCRIPTION
**Pull request by lukadschaak**
This is merge request for importing [pimcore-docker-compose](https://github.com/dpfaffenbauer/pimcore-docker-compose) project by dpfaffenbauer.

Mentioned in #12 by @yariksheptykin @dpfaffenbauer @brusch 

We wanted to preserve the commit history of pimcore-docker-compose, except README.md.
We did this by following commands:

```
git clone https://github.com/dpfaffenbauer/pimcore-docker-compose.git
cd pimcore-docker-compose
git filter-branch --tree-filter 'git rm -f README.md' -- --all
```

After that, add the modified repo as remote to the fork and pull from the remote
```
cd skeleton
git remote add pimcore-docker-compose ../pimcore-docker-compose
git pull pimcore-docker-compose master --allow-unrelated-histories
```

### CODE REVIEW

**Comment by yariksheptykin** [comment]
@lukadschaak , since we dropped original REAME.md while importing from dpfafenbauer's repo we should probably extend README of the skeleton with instructions on how to use composer file. What do you think?

**Comment by yariksheptykin** [comment]
Schade dass es mit dem MR nichts geworden. Ich glaube dass es nicht am MR liegt.

**Comment by dpfaffenbauer** [comment]
sorry what? you closed the PR....

**Comment by lukadschaak** [comment]
We thought that adding a simple docker-compose not a big deal and wondered a bit, that there was no reponse. We didn't even know if it's okay to keep the history, or if a single commit would be better. Do you think we should give the pull request more time and reopen it?

**Pull request closed without merging**
