### PR TITLE
Update supervisord.conf

### PR DESCRIPTION
**Pull request by 80982proton**
Add missing pimcore_search_backend_message reciver otherwise searching for relations does not work.

### CODE REVIEW

**Comment by mattamon** [comment]
@80982proton could you please sign the CLA

**Comment by jdreesen** [comment]
When this gets merged, we probably don't need the info box here anymore: https://pimcore.com/docs/platform/Pimcore/Getting_Started/Installation/Docker_Based_Installation/#follow-these-steps

**Comment by fashxp** [comment]
but when for what ever reason the simple search is not installed during installation, this transport won't be there and throwing errors, right?

**Comment by mattamon** [comment]
@fashxp The Backend Search is neither enabled nor installed by default in the skeleton.
As you stated it would result in an error message. Just adding the messenger consume is not enough.

We could update the documentation that if you install skeleton, that you also need to enable and install the bundle.

**Comment by mattamon** [comment]
@80982proton I will close this PR now. See the following comment for details. https://github.com/pimcore/skeleton/pull/182#issuecomment-2014683655

For future PRs please also make sure to sign the CLA since we cannot accept PRs without it.

**Pull request closed without merging**
