### PR TITLE
Automatically execute bundle migrations on composer update

### PR DESCRIPTION
**Pull request by BlackbitDevs**
This PR calls the Composer script to execute bundle migrations when executing `composer update`.

### CODE REVIEW

**Comment by BlackbitNeueMedien** [comment]
As https://github.com/pimcore/pimcore/pull/6251 is merged now, it would be cool if this PR would also get merged - so we would achieve same behaviour for Pimcore core migrations and bundle migrations.

**Review by yariksheptykin — APPROVED** [review]

**Comment by BlackbitNeueMedien** [comment]
Any news on this @brusch? With the coming major release I think it is a good time for this, don't you?

**Comment by NiklasBr** [comment]
Using this in Pimcore 10 would be nice.

**Comment by brusch** [comment]
Pimcore\\Composer::executeBundleMigrationsUp was removed in Pimcore 10 as we migrated to standard Doctrine Migrations Bundle. 
Running all migrations in one go is now as easy as: 
```bash
bin/console doctrine:migrations:migrate
```

if you prefer to run them automatically after `composer update` I'd just add this to your `composer.json`: 
```json
        "post-update-cmd": [
            "./bin/console doctrine:migrations:migrate"
        ]
```

But since this highly depends on the deployment strategy and use-case I'd not include this in the standard distribution.

**Comment by BlackbitDevs** [comment]
@brusch Just stumbled upon this again. Why do we have https://github.com/pimcore/skeleton/blob/469496120e95dd7755d7368c3ac168363ede20b0/composer.json#L34 in the composer.json but not execute bundle migrations automatically? 

You said
> But since this highly depends on the deployment strategy and use-case I'd not include this in the standard distribution.

But doesn't this apply to core and to bundle migrations?

**Comment by brusch** [comment]
@BlackbitNeueMedien you are right - we should remove that in Pimcore 11.

**Pull request closed without merging**
