### PR TITLE
New .env process

### PR DESCRIPTION
**Pull request by Yivan**
Hello,

It is the pull request to resolve:
https://github.com/pimcore/pimcore/issues/4642
and
https://github.com/pimcore/pimcore/issues/4500 (added default env variables which allow to easily configure proxies)

Tested, and work well with .env.local : )

This PR is only based on default symfony 4 recommendation:
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/public/index.php
https://github.com/symfony/recipes/blob/master/symfony/flex/1.0/.env
https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console
Resumed here:
https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application

Thanks.

I think this PR should be duplicated on other pimcore skeleton (site, twig, ecommerce...)
This doc section needs to be updated: https://pimcore.com/docs/6.x/Development_Documentation/Deployment/Multi_Environment.html#page_section_9
As well https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/V5_to_V6.html or a new Within V6 update maybe (even if this is optionnal... it need manual update of files and change to .gitignore).

### CODE REVIEW

**Comment by brusch** [comment]
Due to https://github.com/pimcore/pimcore/pull/4665 the changes in `bin/console` `web/app.php` and `app/bootstrap.php` are not necessary, can you please update our PR? 

If this PR is approved, please also create a PR for: 
https://github.com/pimcore/demo-basic
https://github.com/pimcore/demo-basic-twig
https://github.com/pimcore/demo-ecommerce

Thanks!

**Comment by Yivan** [comment]
Great, ok i do it now i remove the modification done on bin/console, web/app.php and app/bootstrap.php.

**Comment by Yivan** [comment]
@brusch 

Can i keep this part in app.php ?

```
if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? $_ENV['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}
if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? $_ENV['TRUSTED_HOSTS'] ?? false) {
    Request::setTrustedHosts([$trustedHosts]);
}
```
(official recommendation as it is in the default symfony index file now: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/public/index.php)
And this code was to resolve pimcore/pimcore#4500 too.

**Comment by brusch** [comment]
@Yivan we'll do that as well in `Pimcore\Bootstrap` so you can kick it here.

**Comment by Yivan** [comment]
@brush ok it is done !

**Comment by brusch** [comment]
@Yivan Thanks!

**Comment by brusch** [comment]
All the other demos are updated as well.

**Pull request merged**
