### PR TITLE
Redirect to Pimcore backend when calling the Pimcore main domain without any path

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Currently it is confusing when people try to call their Pimcore under `my-pimcore.org` and then just see an empty site when they expected to get the Pimcore backend. This is because by default currently the DefaultController::defaultAction is a dummy frontend page. This PR redirects to `my-pimcore.org/admin` by default. And if customers want to use the frontend / CMS part of Pimcore, they can select a different controller action for the `/` document (or for the sites).

### CODE REVIEW

**Comment by brusch** [comment]
Not sure if this is really helpful, ev. in cause you create an empty document and the default controller get's applied, then this document just redirects to `/admin`.

**Comment by BlackbitDevs** [comment]
Hmm ok. Perhaps there is another solution but do you see the UX problem when you call `https://my-pimcore.org` and simply see nothing?

**Comment by brusch** [comment]
Yes, but I'm not sure if redirecting to `/admin` makes it better in all cases 😊
How are other systems dealing with that?

**Comment by BlackbitDevs** [comment]
> How are other systems dealing with that?

That is actually difficult because one of the main advantages of Pimcore is that you can use it as pure PIM system but also as CMS / Website with backend. Most other systems are either pure PIM systems (and you get a login when you get to the start page / open application) or you get the normal CMS startpage. As Pimcore is a hybrid solution (which is actually great) we cannot take over a solution of another app.

What do you think of redirecting to `/admin` when you install Pimcore via `pimcore/skeleton` without demo data but using the current defaultAction with the example page when you install Pimcore with `pimcore/demo`?

**Comment by dvesh3** [comment]
@brusch @BlackbitNeueMedien how about we put admin link(describing the backend functionality in one liner or so) on the default page?

**Comment by BlackbitDevs** [comment]
Link is also a good idea but I decided against it for now as it would mean another click. As you said, probably the redirect is not the best way, so I have changed it to forwarding to the `LoginController` internally. This way you see the same content on the home page as on `/admin/login`.
And I provided the old behaviour with the `contentAction()` method.

This way it is transparent why the login form gets shown on the home page and it can easily be changed by altering the `DefaultController::defaultAction()`.

**Comment by brusch** [comment]
What about redirecting only if Kernel has `debug=true` ?
And we call the action `adminRedirectAction()`?

**Comment by BlackbitDevs** [comment]
> What about redirecting only if Kernel has debug=true ?

Won't help. The use-case which I am thinking of is that a company with > 100 employees who work in Pimcore tells them: "You can access our Pimcore at https://pimcore.example.org". When then the employee only sees a white page without any further notice where to get to the admin area, it is quite frustrating.
And always keeping `debug=true` will slow things down during daily work.

What is the reason why you do not like the current approach of this PR? If there is a valid one, perhaps we can agree on what @dvesh3 said: 
> how about we put admin link(describing the backend functionality in one liner or so) on the default page

But to me this would not be as convenient - especially as we see a lot of customers nowadays which only use Pimcore as a PIM system without any frontend.

**Comment by brusch** [comment]
I'll close this for now. Please feel free to continue the discussion.

**Pull request closed without merging**
